### PR TITLE
Created Control Window

### PR DESCRIPTION
**Pull request by neerajanand321**
Created a simple control window to adjust the colour and size of the pen using the Opencv trackbar function and there is also an option to save the final image and quit.

https://user-images.githubusercontent.com/78193865/135800245-fe1e778b-72dc-4e1e-be32-9b984022bf10.mp4

### CODE REVIEW

**Comment by gursi26** [comment]
Hi! This looks great, but maybe you could make it such that changing the sliders only affects things drawn thereafter (i.e. The points already in the list need not be edited, only the points that are newly added). 
With the current method, all drawings are restricted to a single colour. 

Maybe you could implement this by having a list parallel to the one storing the coordinates that would store details related to that point (colour, thickness, etc) and then draw them on each frame, referring to both lists (the first one for the location and the second list for the appearance of the point).

Also, would it be possible to implement the save function as a button rather than a slider?

**Comment by neerajanand321** [comment]
Hey! Thanks and I'll try to do the changes you suggested.

**Comment by gursi26** [comment]
Also, try to include a knob that controls the variable `intermediate_step_gap`, taking values between 0.1 and 5. This variable was created in [this](https://github.com/gursi26/virtual_drawing_board/pull/15) PR

**Comment by neerajanand321** [comment]
Hi! I included another trackbar function for immediate_step_gap and also create a button for saving the image and now trying to fix the issue of restriction to a single colour.
Screenshot 2021-10-04 at 5 01 14 PM

**Comment by gursi26** [comment]
Hi! Great job, looks good so far. Looking forward to your PR.

**Comment by neerajanand321** [comment]
Hi! I made all the required corrections, Please review it.

https://user-images.githubusercontent.com/78193865/135879923-50a73ac3-8937-48c4-8a47-8d8d36d1c179.mp4

**Comment by gursi26** [comment]
Hi! I have had a look at the changes, here are a few things I have noticed. 

- The colouring and changing of thickness is working as intended, great job on that. 
- It looks like the erase function is no longer working (when you ball your hand up into a fist and the box appears, dots within the box are no longer being erased, you can refer to the README for a demo of this function). Please look into this and try to fix it. 
- The imd_step_gap needs to range from values between 0.1 to approximately 2 or 3. It should ideally increase in increments of 0.1, for the change to be noticeable. The ideal value for this parameter would be around 1, which I cannot currently set it to since the slider ranges from 2 to 50. Maybe you could allow it to change from 1 to 30 and then divide the integer value at each step by 10 so that it ranges in intervals of 0.1.
- After you have finished, please do remove any print statements you may have added to verify the buttons are working.

**Comment by neerajanand321** [comment]
Hi! I corrected the issue of Erase function and also made the range of imd_step_gap between 0.1 to 3 and also removed the print statements. Hope this time everything works fine and thanks a lot for being so supportive😊.

**Comment by gursi26** [comment]
Hi! I am extremely happy with the changes now, you have done a great job. Thank you for contributing to this repo!

**Pull request merged**
